---
title: "HW1"
author: "Ophelia Li"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
        html_document
---

```{r}
rm(list= ls())
# Well donw!
# You can put your text lines out of the code blocks, just like how you write a report.
# I made a few edits as an example for you.
```

##1 (a)

0.7 in binary is 0.10110011001

0.2 in binary is 0.00110011001

0.1 in binary is 0.00011001100


##1 (b) (c) (d)

```{r}
(0.7+0.2)+0.1==1
0.7+(0.2+0.1)==1
(0.7+0.1)+0.2==1
```

##1 (e) 

0.7, 0.2, 0.1 are binary floating-point numbers. For the partial sum of 0.7 + 0.2, we lost the last two digis of 0.2 when we align the exponents. Then we add 0.1 to the partial sum and we lost three digits from 0.1 when we align the exponents. The final result is not exactly equal to 1.


```{r}
#2 (a)
library(ggplot2)
x=seq(from=0.988, to=1.012, by=0.001)
y1=x^7 - 7 * x^6 + 21 * x^5 - 35 * x^4 + 35 * x^3 - 21 * x^2 + 7 * x - 1
qplot(x, y1)
#2 (b)
y2=(x - 1)^7
qplot(x, y2)
#2 (c) the first graph y1 does not look like polynomials because we have roundoff errors. It takes differences of very close numbers and lose precision.

#3 (a)
u=c(1, 2, 3, 3, 2, 1)
as.numeric(t(u) %*% u)
#3 (b)
U=diag(6) - (2 / as.numeric(t(u) %*% u)) * u %*% t(u)
# Find the largest off-diagonal elements of U*U
M=U %*% U
max(M[col(M) != row(M)])
# Find the smallest off-diagonal elements of U*U
min(M[col(M) != row(M)])
#3 (c)
max(diag(M))
min(diag(M))
#3 (d)
U %*% u
#3 (e)
max(colSums(abs(U)))
#3 (f)
U[3, ]
#3 (g)
U[3:6, 2]
#3 (h)
A=U[, 1:3]
P=A %*% t(A)
print(P)
#3 (i)
P %*% P - P
#3 (j)
B=U[, 4:6]
Q=B %*% t(B)
print(Q)
#3 (k)
Q %*% Q - Q
#3 (l)
P + Q

#4
oringp=read.table(file="oringp.dat", 
                  col.names = c("flightNumber","date","numberOrings","numberFailed","tempAtLaunch"))
cor(oringp$numberFailed[-24],oringp$tempAtLaunch[-24])

#5 (a) three parts:the body() , the code inside the function. the formals() , the list of arguments which controls how you can call the function. the environment() , the “map” of the location of the function's variables.
#5 (b) the code returns 11
#5 (c) rewrite to:
mean(c(1:10, NA), na.rm = TRUE)
#5 (d)
f2 <- function(a, b) {
  return(a * 10)
}
f2(10, stop("This is an  error!"))
#this function does not throw an error when called. the second argument is never used.

#6 (a)
A=function(n){
  B=matrix(nrow = n, ncol = n)
  for (i in 1:n){
    for (j in 1:n){
      B[i,j]=1/(abs(i-j)+1)
    }
  }
  return(B)
}
#6 (b)
B=A(10)
B
#6 (c)
chol(B)
#6 (d)
det(B)
```